config/routes.rb
FlikrLikr::Application.routes.draw do

  resources :dashboards, :searches, :photos, :tags

  get '/'=>'home#index'

 post '/searches/:id'=>'searches#update', :as=>'update_search'

 root :to=>'home#index'
end

app/models/dashboard.rb
# == Schema Information
#
# Table name: dashboards
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Dashboard < ActiveRecord::Base
  attr_accessible :name
  has_many :searches
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  url        :text
#  status     :string(255)
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Photo < ActiveRecord::Base
  attr_accessible :title, :url, :status, :search_id
  has_and_belongs_to_many :tags
  belongs_to :search
end

app/models/search.rb
# == Schema Information
#
# Table name: searches
#
#  id                :integer          not null, primary key
#  text              :string(255)
#  num_likes         :integer
#  num_dislikes      :integer
#  num_neutral       :integer
#  num_photos_viewed :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Search < ActiveRecord::Base
  attr_accessible :text, :random?, :num_likes, :num_dislikes, :num_neutral
  has_many :photos
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id           :integer          not null, primary key
#  text         :string(255)
#  count        :integer
#  num_likes    :integer
#  num_dislikes :integer
#  num_neutral  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Tag < ActiveRecord::Base
  attr_accessible :text, :count, :num_likes, :num_dislikes, :num_neutral
  has_and_belongs_to_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  # Accesses Flickr and retrieves 100 of the most recent Flickr files.
  # Filters photos by removing photos with empty tags and that don't have a large-sized URL.
  # Also shuffles the photos.`
  def format_photos(photos)
    #photos = flickr.photos.getRecent(:extras=>'tags,url_c')
    photos.reject {|photo| Photo.exists?(:url=>build_urls(photo)) || photo.tags == '' ||  photo.tags.nil? || photo.tags.include?('uploaded') || photo.tags.include?('filter=none') || photo.tags.include?('filter=nofilter')}

    #photos.shuffle
  end

  # receives a Hash object of photos and returns an array of urls. It also builds the URL.
  def build_urls(photos)
    if photos.is_a?(Array)
      new_photos = photos.map {|photo| "http://farm#{photo['farm']}.staticflickr.com/#{photo['server']}/#{photo['id']}_#{photo['secret']}.jpg"}
    else
      "http://farm#{photos['farm']}.staticflickr.com/#{photos['server']}/#{photos['id']}_#{photos['secret']}.jpg"
    end
  end
end

app/controllers/dashboard_controllers.rb
class DashboardController < ApplicationController
  def index
  end
  def new
  end
  def create
  end
  def update
  end
  def edit
  end
  def show
  end
  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      FlickRaw.api_key = "756092d22ac3734e2746938aeb7b2488"
      FlickRaw.shared_secret = "c799cf3e0a721081"
      @photos = flickr.photos.getRecent
      @photos = @photos.to_a
      @urls = build_urls(@photos)
      @photos = @urls.slice(10)
  end
  def new
  end
  def create
  end
  def update
  end
  def edit
  end
  def show
  end
  def destroy
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.order('created_at DESC')
  end
  def new
  end
  def create
  end
  def update
    binding.pry
    redirect_to search_path(params[:id])
  end
  def edit
  end
  def show
    @photo = Photo.find(params[:id])
  end
  def destroy
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   def index
  end


  # Create a new search
  # Determine whether its a random or a keyword search
  # if a random search then create Photo objects limiting
  # Strip out URLs without tags.

  def new
    @search = Search.create
    @search.text = params[:q] || 'random'
    @search.save
    redirect_to search_path(@search.id)
  end

    # Create a photo object
    # Determine whether its liked or disliked
    # Save photo to database
    # Parse Tag string into individual Tag objects
    # save tags to photo object

  def update
    @search = Search.find(params[:id])
    @photo = Photo.find(params[:photo_id])
    @photo.status = params[:commit].downcase
    Search.find(params[:id]).photos << @photo
    tags = params[:tags].split(" ")
    tags.each do |tag|
      @tag = Tag.where(:text=>tag).first || Tag.create(:text=>tag)
      @photo.status == 'like' ? @tag.num_likes +=1 : @tag.num_dislikes += 1
      @tag.save
      @photo.tags << @tag
    end
    @photo.comment = params[:comment]
    @photo.save
    redirect_to search_path(params[:id])
  end

  def edit
  end

  def show
    @search = Search.find(params[:id])
    photos = ''
    url = ''
    @photo = Photo.create
    if @search.text != 'random'
      photos = flickr.photos.search(:text=>@search.text,:extras=>'tags',:accuracy=>3)
    else
      photos = flickr.photos.getRecent(:extras=>'tags,url_c')
    end
    chosen_photo = format_photos(photos).shuffle.first
    @photo.url = build_urls(chosen_photo)
    @photo.title = chosen_photo.title
    @tags = chosen_photo.tags.split(' ')
    @photo.save
  end

  def destroy
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.order(:num_likes).all.reverse
  end
  def new
  end
  def create
  end
  def update
  end
  def edit
  end
  def show
    @tag = Tag.find(params[:id])
  end
  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
 <div class="row">
    <div class="twelve columns">
      <!-- <div id='slider'>
        <div class="slide">Here is the width and height</div>
        <div class="slide">&nbsp;</div>
        <div class="slide">&nbsp;</div>
      </div> -->
      <div id="slider">
       <img class='slide' src='/assets/slide01.jpg' />
       <img class='slide' src='/assets/slide02.jpg' />
       <img class='slide' src='/assets/slide03.jpg' />
       <img class='slide' src='/assets/slide04.jpg' />




<!--
        <img src="/assets/flowers_st_louis.jpg" />
        <img src="/assets/grand_canyon01.jpg" />
        <img src="/assets/san_diego_skyline.jpg" />
        <img src="http://placehold.it/1000x400&text=[img 1]" />
        <img src="http://placehold.it/1000x400&text=[img 2]" />
        <img src="http://placehold.it/1000x400&text=[img 3]" />
        <img src="http://placehold.it/1000x400&text=[img 4]" />
        <div>This is a div</div> -->
      </div>

      <hr />
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlikrLikr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class="twelve columns">
        <h1>FlickrLikr</h1>
      </div>
    </div>
    <div class='row'>
      <div class='eleven columns'>
       <%= form_tag(new_search_path, :method=>'get') do %>
              <%= label_tag(:q, "Search for:") %>
              <%= text_field_tag(:q) %>
        </div>
        <div class='one columns' style='margin-top:20px;'><%= submit_tag("Go!") %></div>
        <% end %>

      </div>
    <div class='row'>
      <div class='twelve columns'>
         <dl class="tabs pill">
            <nav>
              <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Or Search Randomly", new_search_path %></li>
                <li><%= link_to "View Recent Photos", photos_path %></li>
                <li><%= link_to "View Recent Tags", tags_path %></li>

              </ul>
            </nav>
          </dl>
        </div>
      </div>

        <%= yield %>


  </div>
  <script type="text/javascript">
     $(window).load(function() {
         $('#slider').orbit();
     });
  </script>
</body>
</html>

app/views/photos/index.html.erb
<div class='row'>
  <div class='twelve columns'>
    <% @photos.each do |photo| %>
      <%= link_to(image_tag(photo.url, :class=>'indexed_photos'), photo_path(photo.id))%>

    <% end %>
</div>
</div>

app/views/photos/show.html.erb
<div class='row'>
  <div class='eight columns'>
    <%= image_tag @photo.url %>
  </div>
  <div class='four columns'>
    <h1><%= @photo.title %></h1>
    <div>You viewed this on <%= @photo.updated_at %></div>
    <div>You <%= @photo.status %> this photo.</div>
    <div>Tags: <% @photo.tags.each do |tag| %>
        <%= tag.text %>
    <% end %></div>
    <% if @photo.comment? %>
    <div style='border-bottom:1px solid black;margin-top:10px;'>Comments:</div>
    <div><%= @photo.comment %></div>
    <% end %>

  </div>
</div>

app/views/searches/create.html.erb
<div style='float:left;'>
<img src='<%= @photo %>' /></div>
<%= @tags %>
<%= button_to "Like", search_path(@search.id), :name=>'like', :method=>'get' %>

app/views/searches/index.html.erb
Search - got here.

app/views/searches/new.html.erb
<div style='float:left;'>
<img src='<%= @photo %>' /></div>
<%= @tags %>

app/views/searches/show.html.erb
<!-- <div style='float:left;'> -->
<div class='row'>
  <div class='seven columns'>
    <img src='<%= @photo.url %>' name='<%= @photo.id %>' style='border:5px solid #000' />
  </div>
  <div class="five columns">
    <div><h2><%= @photo.title %></h2></div>
    <div style="background-color:lightblue;">Tags</div>
    <div style='padding:10px;'>
    <% @tags.each do|tag| %>
      <%= tag %>
    <% end %>
    </div>
    <%= form_tag search_path, :comment=>'comment', :photo_id=>@photo.id %>
      <%= hidden_field_tag 'photo_id', @photo.id %>
      <%= hidden_field_tag 'tags', @tags %>
      <%= text_field_tag "comment", nil, :placeholder=>"Enter Your Comments here" %>
        <div class='button-bar'>
        <ul class='button-group'>
          <li><%= submit_tag "Like", {:method=>'put', :status=>'like', :tags=>@tags, :photo_id=>@photo.id, :class=>'button'} %></li>
          <li><%= submit_tag "Dislike",{ :method=>'put', :status=>'dislike', :tags=>@tags, :photo_id=>@photo.id, :class=>'button alert'} %></li>
        </ul>
      </div>
  </div>
</div>

app/views/tags/index.html.erb
<table>
  <tr><td>Tag</td><td>Likes</td><td>Dislikes</td></tr>
  <% @tags.each do |tag| %>
  <tr style="background-color:<%= cycle('#ccc','#fff') %>">
    <td><%= link_to tag.text, tag_path(tag.id) %></td><td><%= tag.num_likes %></td><td><%= tag.num_dislikes %></td>
  </tr>
<% end %>
</table>

app/views/tags/show.html.erb
<% @tag.photos.each do |photo| %>
  <%= link_to(image_tag(photo.url, :class=>'tags_show_images'), photo_path(photo.id)) %>
<% end %>